### ISSUE TITLE
memoizeOne is not a function

### ISSUE THREAD

**Issue by mschipperheyn** [microlinkhq/metascraper#255]
### Prerequisites

- [x ] I'm using the last version.
- [ x] My node version is the same as declared as `package.json`.

### Subject of the issue

```
TypeError: memoizeOne is not a function

  685 | /******/
  686 | /******/ 		// Execute the module function
> 687 | /******/ 		modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  688 | /******/
  689 | /******/ 		// Flag the module as loaded
  690 | /******/ 		module.l = true;

    at eval (webpack-internal:///../../node_modules/@metascraper/helpers/index.js:224:16)
    at Object.../../node_modules/@metascraper/helpers/index.js (/Users/mschipperheyn/eclipse-workspace/project-rnw/packages/server/build/server.js:78113:1)
    at __webpack_require__ (/Users/mschipperheyn/eclipse-workspace/project-rnw/packages/server/build/server.js:687:30)
    at fn (/Users/mschipperheyn/eclipse-workspace/project-rnw/packages/server/build/server.js:61:20)
    at eval (webpack-internal:///../../node_modules/metascraper/src/index.js:3:19)
    at Object.../../node_modules/metascraper/src/index.js (/Users/mschipperheyn/eclipse-workspace/project-rnw/packages/server/build/server.js:125170:1)
    at __webpack_require__ (/Users/mschipperheyn/eclipse-workspace/project-rnw/packages/server/build/server.js:687:30)
    at fn (/Users/mschipperheyn/eclipse-workspace/project-rnw/packages/server/build/server.js:61:20)
    at eval (webpack-internal:///./src/server/middleware/remoteUrl/index.js:4:69)
    at Module../src/server/middleware/remoteUrl/index.js (/Users/mschipperheyn/eclipse-workspace/project-rnw/packages/server/build/server.js:15721
```
### Steps to reproduce

I use 
- razzle
- node 12.13.1

I use babel to transpile server side es6.

This looks like an import issue based on the compiled version of memoizeOne. Perhaps it has to do with the fact that I use es6 server side. I've read elsewhere that it might be related to hot reloading. I use razzle and encountered this issue upgrading metascraper. I will downgrade metascraper to a version pre memoizeOne to see if that works.

### Expected behaviour

Import memoizeOne without issue.

### Actual behaviour

Server start up failure due to import failure.

**Comment by mschipperheyn** [comment]
Tried a bunch of versions but the last version that I can get to work is 5.4.7.

**Comment by Kikobeats** [comment]
can you try just transpile `memoizeOne`?

**Comment by mschipperheyn** [comment]
Tried adding it to my webpack babel-loader, but something didn't work or "it" didn't work. Can't really spend more time on this. Prob wouldn't have this issue on the esm module. But not sure how to select this without fucking around a lot.

**Comment by Kikobeats** [comment]
I'm sorry but I'm not going to spend time on this since this package is oriented to run on server side.

There are a lot of internal things that depends of Node.js; I'm sure they can be transpiled with webpack and friend but again browser target is not the goal the project
