### ISSUE TITLE
Unable to expose method "then" on importing metascraper-readability

### ISSUE THREAD

**Issue by jvandenaardweg** [microlinkhq/metascraper#262]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

```
"metascraper": "^5.11.0",
"metascraper-author": "^5.10.7",
"metascraper-date": "^5.10.7",
"metascraper-description": "^5.11.0",
"metascraper-image": "^5.10.7",
"metascraper-publisher": "^5.10.7",
"metascraper-readability": "^5.11.0",
"metascraper-title": "^5.10.7",
"metascraper-url": "^5.10.7",
```

### Subject of the issue
When upgrading from `5.9.5` to `5.11.0`/ `5.10.7` (latest version of all packages) and running my app after that, i notice this error

```
Unable to expose method "then"
```

The error comes from:

```
const metascraper = require('metascraper')([
  require('metascraper-author')(), 
  require('metascraper-description')(), 
  require('metascraper-image')(), 
  require('metascraper-publisher')(), 
  require('metascraper-title')(), 
  require('metascraper-url')(), 
  require('metascraper-readability')(), 
  require('metascraper-date')()
]);

at Object.plumbing.exposePromiseMethod (node_modules/metascraper-readability/node_modules/request-promise-core/lib/plumbing.js:140:19)
at Object.<anonymous>.module.exports (node_modules/metascraper-readability/node_modules/request-promise-core/configure/request2.js:57:83)
at Object.<anonymous> (node_modules/metascraper-readability/node_modules/request-promise-native/lib/rp.js:15:1)
at Object.<anonymous> (node_modules/metascraper-readability/node_modules/jsdom/lib/jsdom/browser/resources/resource-loader.js:5:17)
at Object.<anonymous> (node_modules/metascraper-readability/node_modules/jsdom/lib/api.js:16:24)
at Object.<anonymous> (node_modules/metascraper-readability/index.js:6:15)
at Object.<anonymous> (src/utils/metadata.ts:2:246)
```

### Steps to reproduce
Include the `metascraper-readability` package

### Expected behaviour
No error

### Actual behaviour
Error: `Unable to expose method "then"`

**Comment by jvandenaardweg** [comment]
I notice it's maybe related to a `jsdom` update on `metascraper-readability`. 

When updating my local `jsdom` version to `16.1.0` i get the same error on `5.9.5`, the version that worked before updating `jsdom`.

**Comment by Kikobeats** [comment]
Hello,

Can you share the URL that throw you the error?

We have some [metascraper readability tests](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-readability/test/index.js) and they are passing [green on travis](https://travis-ci.com/microlinkhq/metascraper/builds/147088974), so I need to reproduce the same scenario.

**Comment by Kikobeats** [comment]
closing until the author provides more information to make the error reproducible.

**Comment by jvandenaardweg** [comment]
No url, just running the node app gives the error.
