### ISSUE TITLE
TypeError: Expected `milliseconds` to be a positive number

### ISSUE THREAD

**Issue by yafp** [microlinkhq/metascraper#280]
### Prerequisites

- [ x ] I'm using the last version.
- [ x ] My node version is the same as declared as `package.json`.

### Subject of the issue

Whenever my code is using metascraper to fetch metadata for an url it seems to cause an unhandled promise rejection.
TypeError: Expected `milliseconds` to be a positive number

TypeError: Expected `milliseconds` to be a positive number
    at /home/x/foo/media-dupes/node_modules/p-timeout/index.js:14:9
    at new Promise (<anonymous>)
    at pTimeout (/home/x/foo/media-dupes/node_modules/p-timeout/index.js:12:55)
    at /home/x/foo/media-dupes/node_modules/metascraper-media-provider/src/get-media/provider/generic.js:63:12
    at /home/x/foo/media-dupes/node_modules/metascraper-media-provider/src/get-media/index.js:13:42
    at memoized (/home/x/foo/media-dupes/node_modules/memoize-one/dist/memoize-one.cjs.js:29:31)
    at author (/home/x/foo/media-dupes/node_modules/metascraper-media-provider/src/index.js:108:48)
    at getValue (/home/x/foo/media-dupes/node_modules/metascraper/src/get-data.js:18:21)
    at /home/x/foo/media-dupes/node_modules/metascraper/src/get-data.js:30:27
    at arrayMap (/home/x/foo/media-dupes/node_modules/lodash/lodash.js:639:23)
    at map (/home/x/foo/media-dupes/node_modules/lodash/lodash.js:9554:14)
    at getData (/home/x/foo/media-dupes/node_modules/metascraper/src/get-data.js:29:5)
    at /home/x/foo/media-dupes/node_modules/metascraper/src/index.js:22:12
    at /home/x/foo/media-dupes/app/js/modules/ui.js:1138:32

### Steps to reproduce

Tell us how to reproduce this issue.

### Expected behaviour

It worked in the past - but seems broken since the latest updates

### Actual behaviour

Should not cause a type error ;)

**Comment by Kikobeats** [comment]
@yafp thanks for reporting. It should be fixed at `v5.12.7`, can you confirm?

**Comment by yafp** [comment]
@Kikobeats can confirm - seems fixed. Thank you very much for the quick support & update.
