### ISSUE TITLE
TypeError: resultFn.apply is not a function

### ISSUE THREAD

**Issue by mschipperheyn** [microlinkhq/metascraper#376]
### Prerequisites

- [x ] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

```
const metas = metascraper([
	metascraperYoutube(),
	metascraperTitle(),
	metascraperImage(),
	metascraperDescription(),
	metascraperUrl(),
]);
```

I get an error on retrieving the url:
```
TypeError: resultFn.apply is not a function
    at memoized (/Users/mschipperheyn/project/packages/server/Users/mschipperheyn/project/node_modules/memoize-one/dist/memoize-one.esm.js:28:1)
    at /Users/mschipperheyn/project/packages/server/build/webpack:/Users/mschipperheyn/project/node_modules/metascraper-youtube/index.js:36:1
    at memoized (/Users/mschipperheyn/project/packages/server/build/webpack:/Users/mschipperheyn/project/node_modules/memoize-one/dist/memoize-one.esm.js:28:1)
    at rules.test (/Users/mschipperheyn/project/packages/server/build/webpack:/Users/mschipperheyn/project/node_modules/metascraper-youtube/index.js:55:1)
    at getValue (/Users/mschipperheyn/project/packages/server/build/webpack:/Users/mschipperheyn/project/node_modules/metascraper/src/get-data.js:16:1)
    at /Users/mschipperheyn/project/packages/server/build/webpack:/Users/mschipperheyn/project/node_modules/metascraper/src/get-data.js:29:1
    at arrayMap (/Users/mschipperheyn/project/packages/server/build/webpack:/Users/mschipperheyn/project/node_modules/metascraper/node_modules/lodash/lodash.js:653:1)
    at map (/Users/mschipperheyn/project/packages/server/build/webpack:/Users/mschipperheyn/project/node_modules/metascraper/node_modules/lodash/lodash.js:9622:1)
    at getData (/Users/mschipperheyn/project/packages/server/build/webpack:/Users/mschipperheyn/project/node_modules/metascraper/src/get-data.js:28:1)
```

When I output the `resultFn` in memoize-one, I see this:
```
INFO : resultFn url => getVideoInfo(url).service === 'youtube'
INFO : resultFn {}
INFO : resultFn url => getVideoInfo(url).service === 'youtube'
INFO : resultFn {}
INFO : resultFn url => getVideoInfo(url).service === 'youtube'
INFO : resultFn {}
INFO : resultFn url => getVideoInfo(url).service === 'youtube'
INFO : resultFn {}
ERROR: resultFn.apply is not a function
```

When I remove metascraper-youtube from the list, it works
```
const metas = metascraper([
	// metascraperYoutube(),
	metascraperImage(),
	metascraperDescription(),
	metascraperUrl(),
	metascraperTitle(),
]);
```

Note 
### Steps to reproduce

Run the system with and without youtube and insert the url for a regular webpage.

Tell us how to reproduce this issue.

### Expected behaviour

It should not throw

### Actual behaviour

metascraper-youtube puts an object into memoize-one somewhere along the way

**Comment by Kikobeats** [comment]
Hey,

The dependency `memoize-one ` is calling `.apply``

https://github.com/alexreardon/memoize-one/blob/master/src/memoize-one.ts#L25

Looks like your webpack bundle is not bundling the dependency correctly, so it isn't a metascraper issue by itself.

**Comment by mschipperheyn** [comment]
I'm not saying you can't be right, but you don't think it's odd that this issue doesn't occur when metascraper-youtube is excluded?
