### ISSUE TITLE
incorrect header check

### ISSUE THREAD

**Issue by linojon** [microlinkhq/metascraper#498]
### Prerequisites

- [y ] I'm using the last version.
- [y ] My node version is the same as declared as `package.json`.

### Subject of the issue

Describe your issue here.

getting "incorrect header check" on a specific url
https://www.recorder.com/Berkshire-East-wind-turbine-blade-breaks-45164283

### Steps to reproduce

> **Note**: You can reproduce the code using [interactive Node.js shell by Runkit](https://npm.runkit.com/metascraper).

Tell us how to reproduce this issue.

try to scrape https://www.recorder.com/Berkshire-East-wind-turbine-blade-breaks-45164283

### Expected behaviour

Tell us what should happen

should get an image

### Actual behaviour

Tell us what happens instead

catch error message "incorrect header check"

**Comment by linojon** [comment]
code snippet
```
const metascraper = require('metascraper')([require('metascraper-image')()])
import got from 'got'

export async function preview_image_with_timeout(sourceLink, ms = 3000) {
  let data = null

  // https://spin.atomicobject.com/2020/01/16/timeout-promises-nodejs/
  const promiseWithTimeout = (timeoutMs, promise) => {
    let timeoutHandle
    const timeoutPromise = new Promise((resolve, reject) => {
      timeoutHandle = setTimeout(
        () => reject(new Error(`preview_image timed out: ${sourceLink}`)),
        timeoutMs
      )
    })

    return Promise.race([promise(), timeoutPromise]).then((result) => {
      clearTimeout(timeoutHandle)
      return result
    })
  }

  let previewImage = ''
  if (isPresent(sourceLink)) {
    try {
      await promiseWithTimeout(ms, async () => {
        // * using "got"
        const { body: html, url } = await got(sourceLink)
        data = await metascraper({ html, url }) // * Calling metascraper
        console.log('previewImage result', data)
      })
    } catch (e) {
      console.log('previewImage catch', e.message, sourceLink)
    }

    if (data && isPresent(data.image)) {
      previewImage = data.image
    }
  }


  return previewImage
}
```

**Comment by Kikobeats** [comment]
Hello, just tried using [api.microlink.io](https://api.microlink.io/), and it worked:

https://api.microlink.io/?url=https://www.recorder.com/Berkshire-East-wind-turbine-blade-breaks-45164283

what data field are you trying to obtain

**Comment by linojon** [comment]
ok. I now realize the error is coming from the got() call. Here's the full error object. Any suggestions? I'm running this in a Node JS api. Is there source code to api.microlink.io i can review?

```
previewImage catch incorrect header check https://www.recorder.com/Berkshire-East-wind-turbine-blade-breaks-45164283 RequestError: incorrect header check
    at PassThrough.<anonymous> (file:///D:/Documents/JavascriptProjects/WindActionJS/node_modules/got/dist/source/core/index.js:610:31)
    at Object.onceWrapper (events.js:520:26)
    at PassThrough.emit (events.js:412:35)
    at PassThrough.emit (domain.js:475:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at Zlib.zlibOnError [as onerror] (zlib.js:187:17) {
  input: undefined,
  code: 'Z_DATA_ERROR',
  timings: {
    start: 1646134276108,
    socket: 1646134276110,
    lookup: 1646134276112,
    connect: 1646134276182,
    secureConnect: 1646134276389,
    upload: 1646134276391,
    response: 1646134277966,
    end: 1646134277968,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 2,
      tcp: 70,
      tls: 207,
      request: 2,
      firstByte: 1575,
      download: 2,
      total: 1860
    }
  },
  name: 'ReadError',
  options: {
    request: undefined,
    agent: { http: undefined, https: undefined, http2: undefined },
    h2session: undefined,
    decompress: true,
    timeout: {
      connect: undefined,
      lookup: undefined,
      read: undefined,
      request: undefined,
      response: undefined,
      secureConnect: undefined,
      send: undefined,
      socket: undefined
    },
    prefixUrl: '',
    body: undefined,
    form: undefined,
    json: undefined,
    cookieJar: undefined,
    ignoreInvalidCookies: false,
    searchParams: undefined,
    dnsLookup: undefined,
    dnsCache: undefined,
    context: {},
    hooks: {
      init: [],
      beforeRequest: [],
      beforeError: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: []
    },
    followRedirect: true,
    maxRedirects: 10,
    cache: undefined,
    throwHttpErrors: true,
    username: '',
    password: '',
    http2: false,
    allowGetBody: false,
    headers: {
      'user-agent': 'got (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate, br'
    },
    methodRewriting: false,
    dnsLookupIpVersion: undefined,
    parseJson: [Function: parse],
    stringifyJson: [Function: stringify],
    retry: {
      limit: 2,
      methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
      statusCodes: [
        408, 413, 429, 500,
        502, 503, 504, 521,
        522, 524
      ],
      errorCodes: [
        'ETIMEDOUT',
        'ECONNRESET',
        'EADDRINUSE',
        'ECONNREFUSED',
        'EPIPE',
        'ENOTFOUND',
        'ENETUNREACH',
        'EAI_AGAIN'
      ],
      maxRetryAfter: undefined,
      calculateDelay: [Function: calculateDelay],
      backoffLimit: Infinity,
      noise: 100
    },
    localAddress: undefined,
    method: 'GET',
    createConnection: undefined,
    cacheOptions: {
      shared: undefined,
      cacheHeuristic: undefined,
      immutableMinTimeToLive: undefined,
      ignoreCargoCult: undefined
    },
    https: {
      alpnProtocols: undefined,
      rejectUnauthorized: undefined,
      checkServerIdentity: undefined,
      certificateAuthority: undefined,
      key: undefined,
      certificate: undefined,
      passphrase: undefined,
      pfx: undefined,
      ciphers: undefined,
      honorCipherOrder: undefined,
      minVersion: undefined,
      maxVersion: undefined,
      signatureAlgorithms: undefined,
      tlsSessionLifetime: undefined,
      dhparam: undefined,
      ecdhCurve: undefined,
      certificateRevocationLists: undefined
    },
    encoding: undefined,
    resolveBodyOnly: false,
    isStream: false,
    responseType: 'text',
    url: URL {
      href: 'https://www.recorder.com/Berkshire-East-wind-turbine-blade-breaks-45164283',
      origin: 'https://www.recorder.com',
      protocol: 'https:',
      username: '',
      password: '',
      host: 'www.recorder.com',
      hostname: 'www.recorder.com',
      port: '',
      pathname: '/Berkshire-East-wind-turbine-blade-breaks-45164283',
      search: '',
      searchParams: URLSearchParams {},
      hash: ''
    },
    pagination: {
      transform: [Function: transform],
      paginate: [Function: paginate],
      filter: [Function: filter],
      shouldContinue: [Function: shouldContinue],
      countLimit: Infinity,
      backoff: 0,
      requestLimit: 10000,
      stackAllItems: false
    },
    setHost: true,
    maxHeaderSize: undefined
  },
  bufferedData: <Buffer >
}
previewImage catch incorrect header check https://www.recorder.com/Berkshire-East-wind-turbine-blade-breaks-45164283 RequestError: incorrect header check
    at PassThrough.<anonymous> (file:///D:/Documents/JavascriptProjects/WindActionJS/node_modules/got/dist/source/core/index.js:610:31)
    at Object.onceWrapper (events.js:520:26)
    at PassThrough.emit (events.js:412:35)
    at PassThrough.emit (domain.js:475:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at Zlib.zlibOnError [as onerror] (zlib.js:187:17) {
  input: undefined,
  code: 'Z_DATA_ERROR',
  timings: {
    start: 1646134311344,
    socket: 1646134311344,
    lookup: 1646134311345,
    connect: 1646134311396,
    secureConnect: 1646134311451,
    upload: 1646134311452,
    response: 1646134311557,
    end: undefined,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 1,
      tcp: 51,
      tls: 55,
      request: 1,
      firstByte: 105,
      download: undefined,
      total: undefined
    }
  },
  name: 'ReadError',
  options: {
    request: undefined,
    agent: { http: undefined, https: undefined, http2: undefined },
    h2session: undefined,
    decompress: true,
    timeout: {
      connect: undefined,
      lookup: undefined,
      read: undefined,
      request: undefined,
      response: undefined,
      secureConnect: undefined,
      send: undefined,
      socket: undefined
    },
    prefixUrl: '',
    body: undefined,
    form: undefined,
    json: undefined,
    cookieJar: undefined,
    ignoreInvalidCookies: false,
    searchParams: undefined,
    dnsLookup: undefined,
    dnsCache: undefined,
    context: {},
    hooks: {
      init: [],
      beforeRequest: [],
      beforeError: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: []
    },
    followRedirect: true,
    maxRedirects: 10,
    cache: undefined,
    throwHttpErrors: true,
    username: '',
    password: '',
    http2: false,
    allowGetBody: false,
    headers: {
      'user-agent': 'got (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate, br'
    },
    methodRewriting: false,
    dnsLookupIpVersion: undefined,
    parseJson: [Function: parse],
    stringifyJson: [Function: stringify],
    retry: {
      limit: 2,
      methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
      statusCodes: [
        408, 413, 429, 500,
        502, 503, 504, 521,
        522, 524
      ],
      errorCodes: [
        'ETIMEDOUT',
        'ECONNRESET',
        'EADDRINUSE',
        'ECONNREFUSED',
        'EPIPE',
        'ENOTFOUND',
        'ENETUNREACH',
        'EAI_AGAIN'
      ],
      maxRetryAfter: undefined,
      calculateDelay: [Function: calculateDelay],
      backoffLimit: Infinity,
      noise: 100
    },
    localAddress: undefined,
    method: 'GET',
    createConnection: undefined,
    cacheOptions: {
      shared: undefined,
      cacheHeuristic: undefined,
      immutableMinTimeToLive: undefined,
      ignoreCargoCult: undefined
    },
    https: {
      alpnProtocols: undefined,
      rejectUnauthorized: undefined,
      checkServerIdentity: undefined,
      certificateAuthority: undefined,
      key: undefined,
      certificate: undefined,
      passphrase: undefined,
      pfx: undefined,
      ciphers: undefined,
      honorCipherOrder: undefined,
      minVersion: undefined,
      maxVersion: undefined,
      signatureAlgorithms: undefined,
      tlsSessionLifetime: undefined,
      dhparam: undefined,
      ecdhCurve: undefined,
      certificateRevocationLists: undefined
    },
    encoding: undefined,
    resolveBodyOnly: false,
    isStream: false,
    responseType: 'text',
    url: URL {
      href: 'https://www.recorder.com/Berkshire-East-wind-turbine-blade-breaks-45164283',
      origin: 'https://www.recorder.com',
      protocol: 'https:',
      username: '',
      password: '',
      host: 'www.recorder.com',
      hostname: 'www.recorder.com',
      port: '',
      pathname: '/Berkshire-East-wind-turbine-blade-breaks-45164283',
      search: '',
      searchParams: URLSearchParams {},
      hash: ''
    },
    pagination: {
      transform: [Function: transform],
      paginate: [Function: paginate],
      filter: [Function: filter],
      shouldContinue: [Function: shouldContinue],
      countLimit: Infinity,
      backoff: 0,
      requestLimit: 10000,
      stackAllItems: false
    },
    setHost: true,
    maxHeaderSize: undefined
  },
  bufferedData: <Buffer >
}
previewImage catch incorrect header check https://www.recorder.com/Berkshire-East-wind-turbine-blade-breaks-45164283 RequestError: incorrect header check
    at PassThrough.<anonymous> (file:///D:/Documents/JavascriptProjects/WindActionJS/node_modules/got/dist/source/core/index.js:610:31)
    at Object.onceWrapper (events.js:520:26)
    at PassThrough.emit (events.js:412:35)
    at PassThrough.emit (domain.js:475:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at Zlib.zlibOnError [as onerror] (zlib.js:187:17) {
  input: undefined,
  code: 'Z_DATA_ERROR',
  timings: {
    start: 1646135244240,
    socket: 1646135244240,
    lookup: 1646135244574,
    connect: 1646135244624,
    secureConnect: 1646135244728,
    upload: 1646135244728,
    response: 1646135245555,
    end: undefined,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 334,
      tcp: 50,
      tls: 104,
      request: 0,
      firstByte: 827,
      download: undefined,
      total: undefined
    }
  },
  name: 'ReadError',
  options: {
    request: undefined,
    agent: { http: undefined, https: undefined, http2: undefined },
    h2session: undefined,
    decompress: true,
    timeout: {
      connect: undefined,
      lookup: undefined,
      read: undefined,
      request: undefined,
      response: undefined,
      secureConnect: undefined,
      send: undefined,
      socket: undefined
    },
    prefixUrl: '',
    body: undefined,
    form: undefined,
    json: undefined,
    cookieJar: undefined,
    ignoreInvalidCookies: false,
    searchParams: undefined,
    dnsLookup: undefined,
    dnsCache: undefined,
    context: {},
    hooks: {
      init: [],
      beforeRequest: [],
      beforeError: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: []
    },
    followRedirect: true,
    maxRedirects: 10,
    cache: undefined,
    throwHttpErrors: true,
    username: '',
    password: '',
    http2: false,
    allowGetBody: false,
    headers: {
      'user-agent': 'got (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate, br'
    },
    methodRewriting: false,
    dnsLookupIpVersion: undefined,
    parseJson: [Function: parse],
    stringifyJson: [Function: stringify],
    retry: {
      limit: 2,
      methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
      statusCodes: [
        408, 413, 429, 500,
        502, 503, 504, 521,
        522, 524
      ],
      errorCodes: [
        'ETIMEDOUT',
        'ECONNRESET',
        'EADDRINUSE',
        'ECONNREFUSED',
        'EPIPE',
        'ENOTFOUND',
        'ENETUNREACH',
        'EAI_AGAIN'
      ],
      maxRetryAfter: undefined,
      calculateDelay: [Function: calculateDelay],
      backoffLimit: Infinity,
      noise: 100
    },
    localAddress: undefined,
    method: 'GET',
    createConnection: undefined,
    cacheOptions: {
      shared: undefined,
      cacheHeuristic: undefined,
      immutableMinTimeToLive: undefined,
      ignoreCargoCult: undefined
    },
    https: {
      alpnProtocols: undefined,
      rejectUnauthorized: undefined,
      checkServerIdentity: undefined,
      certificateAuthority: undefined,
      key: undefined,
      certificate: undefined,
      passphrase: undefined,
      pfx: undefined,
      ciphers: undefined,
      honorCipherOrder: undefined,
      minVersion: undefined,
      maxVersion: undefined,
      signatureAlgorithms: undefined,
      tlsSessionLifetime: undefined,
      dhparam: undefined,
      ecdhCurve: undefined,
      certificateRevocationLists: undefined
    },
    encoding: undefined,
    resolveBodyOnly: false,
    isStream: false,
    responseType: 'text',
    url: URL {
      href: 'https://www.recorder.com/Berkshire-East-wind-turbine-blade-breaks-45164283',
      origin: 'https://www.recorder.com',
      protocol: 'https:',
      username: '',
      password: '',
      host: 'www.recorder.com',
      hostname: 'www.recorder.com',
      port: '',
      pathname: '/Berkshire-East-wind-turbine-blade-breaks-45164283',
      search: '',
      searchParams: URLSearchParams {},
      hash: ''
    },
    pagination: {
      transform: [Function: transform],
      paginate: [Function: paginate],
      filter: [Function: filter],
      shouldContinue: [Function: shouldContinue],
      countLimit: Infinity,
      backoff: 0,
      requestLimit: 10000,
      stackAllItems: false
    },
    setHost: true,
    maxHeaderSize: undefined
  },
  bufferedData: <Buffer >
}
```

**Comment by linojon** [comment]
hi, "fixed" it! i dont understand but calling got() with  `{ decompress: false } `works on this url, 
```
    try {
      const { body: html, url } = await got(sourceLink, {
        timeout: { request: timeout }
      })
      data = await metascraper({ html, url }) // * Calling metascraper
    } catch (e) {
      console.log('previewImage catch:', e.message, sourceLink)
      // handle "incorrect header check" error eg https://www.recorder.com/Berkshire-East-wind-turbine-blade-breaks-45164283
      try {
        const { body: html, url } = await got(sourceLink, {
          timeout: { request: timeout },
          decompress: false
        })
        data = await metascraper({ html, url }) // * Calling metascraper
      } catch (e) {
        console.log('previewImage catch2:', e.message, sourceLink)
      }
    }
````
