### ISSUE TITLE
Issue on testing using script in bench

### ISSUE THREAD

**Issue by immortal-autumn** [microlinkhq/metascraper#521]
I am using the latest version of metascraper but I am unable to run the test case of the metascraper in the bench folder.

The error message is as follows:

> TypeError: SCRAPER.scrape(...).then is not a function
    at E:\metascraper-5.28.6\metascraper-5.28.6\bench\index.js:90:48
    at Array.map (<anonymous>)
    at getScraperResults (E:\metascraper-5.28.6\metascraper-5.28.6\bench\index.js:86:10)
    at E:\metascraper-5.28.6\metascraper-5.28.6\bench\index.js:65:14
    at Array.map (<anonymous>)
    at getScrapersResults (E:\metascraper-5.28.6\metascraper-5.28.6\bench\index.js:64:14)
    at E:\metascraper-5.28.6\metascraper-5.28.6\bench\index.js:49:12
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

My node version is v16.14.2

**Comment by Kikobeats** [comment]
Hello,

Unfortunately, metascraper evolves a lot and benchmark folder is outdated these days.

I have to schedule some time to make it up to date again.

In any case, metascraper has been optimized a lot for running as fast as possible while add support for more rules and providers.
